version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: wavefinder-web
    restart: unless-stopped
    # Do not publish host ports; Coolify will attach a domain and route to the exposed port below
    expose:
      - "80"
    volumes:
      # Serve the static site directly from the repo
      - ../apps/web:/usr/share/nginx/html:ro
      # Use our nginx config (enables gzip, index fallback, sensible caching)
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # No custom networks or proxy labels here; Coolify manages those for you
